name: Sync Last.fm to Slack

on:
  schedule:
    # Runs every 5 minutes (the maximum frequency allowed by GitHub Actions)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to trigger it manually from GitHub anytime

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run status updater script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          SLACK_NAME: "matt"
        run: node update-status.js
